language: python
python:
    - "2.6"
    - "2.7"
    - "pypy"
    - "3.3"
    - "3.4"

install:
    # Travis uses an outdated PyPy, this installs the most recent one.
    - "[[ ${TRAVIS_PYTHON_VERSION} == pypy ]] && sudo add-apt-repository -y ppa:pypy/ppa || true"
    - "[[ ${TRAVIS_PYTHON_VERSION} == pypy ]] && sudo apt-get -y update && sudo apt-get -y install pypy || true"
    - "[[ ${TRAVIS_PYTHON_VERSION} == pypy ]] && sudo rm -rf /usr/local/pypy/bin || true"
    - pip install tox

script:
    - tox -e $(echo py$TRAVIS_PYTHON_VERSION | tr -d . | sed -e 's/pypypy/pypy/')

branches:
  except:
    - website

notifications:
  email: false
  irc:
    channels:
      - "chat.freenode.net#pocoo"
    on_success: change
    on_failure: always
    use_notice: true
    skip_join: true
